name: KUBESEC
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas=2.0.2
  - pyyaml=6.0
  - pytest=7.3.1
  - requests=2.29.0
  - numpy=1.26.0
  - pip
  - pip:
      - bandit==1.8.2
      - typer
      - sarif_om
      - jschema-to-python
      - ruamel.yaml 