name: Run Fuzz Tests

on:
  push:
    paths:
      - '**/fuzz.py'
      - '.github/workflows/fuzz.yml'

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t slikube ./KubeSec-master/

    - name: Run Fuzzing
      run: docker run --rm -v ${{ github.workspace }}/KubeSec/KubeSec-master/output:/results slikube

    - name: Upload Fuzz Results
      uses: actions/upload-artifact@v3
      with:
        name: fuzz-logs
        path: KubeSec/KubeSec-master/output/


